route:
  receiver: 'null'
  routes:
    - receiver: 'slack-notifications'
      matchers:
        - alertname = "GrafanaIsUnhealthy"
receivers:
- name: 'null'
- name: 'slack-notifications'
  slack_configs:
    - send_resolved: true
      api_url: 'https://hooks.slack.com/services/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'
      text: "<!channel>\n{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
