services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - '9100:9100'

volumes:
  prometheus-data:
